easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
        uri_prefix:         '%app.path.uploads%'
        upload_destination: '%kernel.project_dir%/public/%app.path.uploads%'
